apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  annotations:
    argocd.argoproj.io/sync-wave: "200"
  labels:
    gitops.tier.group: cntk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-serverless
    server: 'https://kubernetes.default.svc'
  project: services
  source:
    path: 2-services/instances
    repoURL: https://github.com/csantanapr/what-is-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true