apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev
  annotations:
    argocd.argoproj.io/sync-wave: "400"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: bookinfo/kustomize/dev
    repoURL: https://github.com/csantanapr/gitops-bookinfo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
